name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Step 1 - Clean
      run: mvn clean

    - name: Step 2 - Validate
      run: mvn validate

    - name: Step 3 - Compile
      run: mvn compile

    - name: Step 4 - Test
      run: mvn test

    - name: Step 5 - Package (Generate Artifact)
      run: mvn package

    - name: Step 6 - Verify
      run: mvn verify

    - name: Step 7 - Install
      run: mvn install

    - name: Step 8 - Site
      run: mvn site

    - name: Step 9 - Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: maven-build-artifact
        path: target/*.jar
